UPDATE `Report`
SET `status` = 'DISETUJUI_FINAL',
    `approvedAt` = COALESCE(`approvedAt`, NOW(3)),
    `finishedAt` = COALESCE(`finishedAt`, NOW(3))
WHERE `status` = 'MENUNGGU_ADMIN_6';

UPDATE `ReportApprovalHistory`
SET `fromStatus` = 'DISETUJUI_FINAL'
WHERE `fromStatus` = 'MENUNGGU_ADMIN_6';

UPDATE `ReportApprovalHistory`
SET `toStatus` = 'DISETUJUI_FINAL'
WHERE `toStatus` = 'MENUNGGU_ADMIN_6';

UPDATE `User`
SET `role` = 'ADMIN_5'
WHERE `role` = 'ADMIN_6';

ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN_1', 'ADMIN_2', 'ADMIN_3', 'ADMIN_4', 'ADMIN_5', 'USER') NOT NULL DEFAULT 'USER';

ALTER TABLE `Report` MODIFY `status` ENUM('MENUNGGU_ADMIN_1', 'MENUNGGU_ADMIN_2', 'MENUNGGU_ADMIN_3', 'MENUNGGU_ADMIN_4', 'MENUNGGU_ADMIN_5', 'DISETUJUI_FINAL', 'DITOLAK') NOT NULL DEFAULT 'MENUNGGU_ADMIN_1';

ALTER TABLE `ReportApprovalHistory` MODIFY `fromStatus` ENUM('MENUNGGU_ADMIN_1', 'MENUNGGU_ADMIN_2', 'MENUNGGU_ADMIN_3', 'MENUNGGU_ADMIN_4', 'MENUNGGU_ADMIN_5', 'DISETUJUI_FINAL', 'DITOLAK') NOT NULL;

ALTER TABLE `ReportApprovalHistory` MODIFY `toStatus` ENUM('MENUNGGU_ADMIN_1', 'MENUNGGU_ADMIN_2', 'MENUNGGU_ADMIN_3', 'MENUNGGU_ADMIN_4', 'MENUNGGU_ADMIN_5', 'DISETUJUI_FINAL', 'DITOLAK') NOT NULL;
